name: Flowing Memories
favicon: null
layout_spectrum: 0.6834684840869159
typography_spectrum: 0.887482458492741
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.14347344124689698
  lightness: 0.7493221315089613
  saturation: 0.24292511935345829
  rhythmicContrast: 0.08466762211173773
purpose: []
